module.exports = {
  container: {
    padding: 20,
    backgroundColor: '#D81A3C',
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  image: {
    width: 18,
    height: 29,
  },
  text: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'black',
    marginVertical: 8,
  },
  checkout: {
    padding: 8,
    marginVertical: 5,
    borderRadius: 20,
    marginVertical: 8,
  },
  textBtn: {
    textAlign: 'center',
    fontSize: 18,
    fontWeight: 'bold',
  },
  btnReset: {
    backgroundColor: 'white',
    borderWidth: 2,
    borderRadius: 20,
    padding: 8,
    alignItems: 'center',
    marginBottom: 5,
  },
  coverFooter: {
    backgroundColor: 'white',
    padding: 15,
    position: 'absolute',
    bottom: -35,
    width: '100%',
    elevation: 8,
    paddingVertical: 13,
  },
  //list
  menuBtn: {
    flexDirection: 'row',
    height: 50,
    alignItems: 'center',
    width: 177,
    justifyContent: 'space-between',
    padding: 5,
    backgroundColor: '#F0F0F0',
    borderRadius: 10,
  },
  btn: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  btnAdd: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
    borderRadius: 8,
  },
  coverList: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'center',
    width: 338,
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 15,
  },
  imgstye: {
    width: 70,
    height: 120,
  },
};
